src/Entity/Entete.php
<?php

namespace App\Entity;

use App\Repository\EnteteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HeaderRepository::class)
 */
class Entete
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $boutonTitre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $boutonUrl;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Illustration;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getBoutonTitre(): ?string
    {
        return $this->boutonTitre;
    }

    public function setBoutonTitre(string $boutonTitre): self
    {
        $this->boutonTitre = $boutonTitre;

        return $this;
    }

    public function getBoutonUrl(): ?string
    {
        return $this->boutonUrl;
    }

    public function setBoutonUrl(string $boutonUrl): self
    {
        $this->boutonUrl = $boutonUrl;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->Illustration;
    }

    public function setIllustration(string $Illustration): self
    {
        $this->Illustration = $Illustration;

        return $this;
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Classe\Panier;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class PanierController extends AbstractController
{

    private $entityManager;

    /**
     * @param $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }


    #[Route('/mon-panier', name: 'panier')]
    public function index(Panier $panier)
    {
        /*dd($panier->get());*/

        /*        dd($panierComplet);*/
        return $this->render('panier/index.html.twig',
            [
                'panier' => $panier->getFull()
            ]);
    }

    #[Route('/panier/add/{id}', name: 'add_to_panier')]
    public function add(Panier $panier, $id)
    {

        $panier->add($id);

        return $this->redirectToRoute('panier');
    }

    #[Route('/panier/delete/{id}', name: 'delete_mon_panier')]
    public function delete(Panier $panier, $id)
    {

        $panier->delete($id);
        return $this->redirectToRoute('panier');
    }

    #[Route('/panier/decrease/{id}', name: 'decrease_mon_panier')]
    public function decrease(Panier $panier, $id)
    {

        $panier->decrease($id);
        return $this->redirectToRoute('panier');
    }
}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon panier - La Boutique  {% endblock %}

{% block content %}

    <h1 class="font-weight-bold text-info">Mon panier</h1>
    <a href="{{ path('produits') }}" class="float-right font-weight-bold ">Retour</a><br>

    {# {{ dump(panier) }} #}
    {% if panier |length > 0 %}
        <table class="table mt-3">
            <thead>
            <tr>
                <th scope="col" class="text-info">Produit</th>
                <th scope="col" class="text-info">Quantité</th>
                <th scope="col" class="text-info">Prix</th>
                <th scope="col" class="text-info">Total</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% set total = null %}
            {% for produit in panier %}
                {# {{  dump(produit)}} #}
                <tr>
                    <th>
                        <img src="/uploads/{{ produit.product.illustration }}" alt="{{ produit.product.nom }}"
                             height="75px"><br>
                    </th>
                    <td class="font-weight-bold">{{ produit.product.nom }}
                        <br>
                        <small class="font-weight-bold">{{ produit.product.subtitle }}</small>
                    </td>
                    <td>

                  {#      Diminuer produit#}
                        <a href="{{ path('decrease_mon_panier', { 'id':produit.product.id}) }}">
                            <img src="{{ asset('assets/image/minus.png') }}" height="15px" alt="Supprimer quantité">
                        </a>
                        <b class="font-weight-bold"> x {{ produit.quantity }}</b>


                  {#      Ajouter produit#}
                        <a  href="{{ path('add_to_panier', { 'id':produit.product.id}) }}" >

                        <img src="{{ asset('assets/image/plus.png') }}" height="15px" alt="Ajouter quantité">
                        </a>
                    </td>
                    <td class="font-weight-bold">{{ (produit.product.prix/ 100) | number_format(2, ',', '.') }} €</td>
                    <td class="font-weight-bold">{{ (produit.product.prix * produit.quantity/ 100) | number_format(2, ',', '.') }} €</td>
                    <td>
                        <a href="{{ path('delete_mon_panier',{'id':produit.product.id}) }}">
                            <img src="{{ asset('assets/image/delete-button.png') }}"  height="18px" alt="Supprimer mon produit">
                        </a>

                    </td>
                </tr>
                {% set total = total + (produit.product.prix * produit.quantity) %}
            {% endfor %}
            </tbody>
        </table>

        <div class="text-right mb-5 font-weight-bold">
            <b> Nombre de produit : {{ panier|length }}</b><br>
            <b> Total : </b>{{ (total/ 100) | number_format(2, ',', '.') }} €<br>

            <a href="{{ path('commande') }}" class="btn btn-success mt-3 font-weight-bold">Valider mon panier</a>
        </div>
    {% else %}
        <hr>
        <p class="mb-5 font-weight-bold"><b>Votre panier est vide.</b></p>
    {% endif %}
{% endblock %}